spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 1038880691615-2hkei3le1fvvshe38ggk4lgrogpjtill.apps.googleusercontent.com
                        client-secret: f_qBXWYTkRHC3FWb-sPtSSxj
                    github:
                        client-id: 818e0475fe72c4574040
                        client-secret: a781432f245a9ffa5834d7fb728c12d1aaffe191
#                        scope: read:user,public_repo                    
        user:
            name: demo
            password: $2a$10$avMRRaZS9U68VIqj50OjV.wjdE.xWHRkJ781m3hzqOZA96gtQc1.2
        
    jpa:
        generate-ddl: false
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
    datasource:
        url: jdbc:mysql://localhost/filesync
        username: root
        password: 12345678
    redis:
        url: redis://127.0.0.1:6379
    cache:
        redis:
            time-to-live: 600000
    rabbitmq:
        username: dev
        password: 1234567
        host: localhost
        virtualHost: /filesync
        port: 5672
#auth:
#    openid:
#        google:
#            client-id: 1038880691615-2hkei3le1fvvshe38ggk4lgrogpjtill.apps.googleusercontent.com
#            client-secret: f_qBXWYTkRHC3FWb-sPtSSxj
logging:
    level:
        org.springframework.web: INFO
        org.springframework.security: INFO
        com.example.demo: TRACE

config:
    amqp:
        queue:
            filesync: filesync
        exchange: file
            
